### ISSUE TITLE
npm i ngx-smooth-dnd

### ISSUE THREAD

**Issue by PhuCuong14ctt** [kutlugsahin/ngx-smooth-dnd#7] opened 2018-06-12 03:51 UTC
Your lib is so awesome but i got a little trouble when i installed

> npm i ngx-smooth-dnd

System saved "ngx-smooth-dnd": "^0.2.0" in my package.json file. It's quite old and cards page couldn't work well as it in demo page.
After that, I downloaded your demo and imported from the lib folder in demo. Now everything seems to be OK.
Moreover, I must copy css from your style.css file manually

I just want to notice if you don't know that because i believe that lib can be used more popular if you have time to take care it.

Thank you so much.

**Comment by kutlugsahin** [comment] 2018-07-23 10:01
Hey @PhuCuong14ctt 
Thanks so much for you comments, I really appreciate it. I admit it needs a bit attention especially with angular 6 version. I will definitely spend some time to make it work well with all the angular version.
Thanks.

**Comment by kutlugsahin** [comment] 2018-07-24 09:32
Please downgrade to version 0.1.9 until the problem fixex

**Comment by kutlugsahin** [comment] 2018-07-29 18:54
@PhuCuong14ctt @jim-cosgrave-web 
The problem is fixed in the version 0.2.1. please upgrade.
Cheers!

**Closed** 2018-08-05 12:58 UTC
